### ISSUE TITLE
KmerIndexBuilder Failed : 1

### ISSUE THREAD

**Issue by ValerieLanglois** [iychoi/libra#5]
Hi, I'm getting the error message "KmerIndexBuilder Failed : 1" on my latest run. Any idea what could be causing this? 

I'm working with a new set of file but the pipeline worked great before with a previous set of about the same size and a little bit less memory (I added 150G to the latest un to try and fix the issue and it didn't work.)

Here is the end of the log file

            Map-Reduce Framework
                    Map input records=17697792
                    Map output records=4221460117
                    Map output bytes=75986282106
                    Map output materialized bytes=38156009748
                    Input split bytes=49056
                    Combine input records=6930579219
                    Combine output records=4616919035
                    Spilled Records=4623911416
                    Failed Shuffles=0
                    Merged Map outputs=0
                    GC time elapsed (ms)=3946
                    Total committed heap usage (bytes)=4048644210688
            File Input Format Counters
                    Bytes Read=10205712556
    2022-01-13 09:53:56,784 ERROR preprocess.Preprocessor: java.lang.Exception: Km
    java.lang.Exception: KmerIndexBuilder Failed : 1
            at libra.preprocess.Preprocessor.run(Preprocessor.java:113)
            at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:76)
            at libra.preprocess.Preprocessor.main(Preprocessor.java:46)
            at libra.Libra.main(Libra.java:74)
            at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Nat
            at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Nati
            at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(
            at java.base/java.lang.reflect.Method.invoke(Method.java:566)
            at org.apache.hadoop.util.RunJar.run(RunJar.java:318)
            at org.apache.hadoop.util.RunJar.main(RunJar.java:232)

**Comment by iychoi** [comment]
Hi @ValerieLanglois 
Can you provide me the full error log file? It looks like the message you shared is cut. 
And can you share your command that used for running Libra?
